/**
 * API key lifecycle — the credentials behind the public HTTP API
 * (Phase 30, Milestone 15).
 *
 * Purpose: the only write path for the `api_keys` table. A key is a
 * bearer credential distinct from the browser session (plan, Phase 30):
 * generated by its owner, shown once, stored only as a SHA-256 hash,
 * and revoked by stamping rather than deleting. Legacy Mingle kept one
 * plaintext `users.api_key` per user regenerated from the profile page;
 * this keeps the profile-driven lifecycle and drops plaintext at rest.
 *
 * Commands → events:
 *   GenerateApiKey → ApiKeyGenerated
 *   RevokeApiKey   → ApiKeyRevoked
 *
 * Since Phase 31 every key is minted with a paired HMAC signing secret
 * (legacy `ApiAuth` parity): the bearer key is hashed at rest, the
 * signing secret is sealed at rest (the server must read it back to
 * verify signatures), and both are shown once.
 *
 * Public interface: `generateApiKey`, `revokeApiKey`,
 * `authenticateApiKey`, `verifySignedRequest`, `listApiKeys`,
 * `API_KEY_PREFIX`.
 *
 * Owner context: Identity & Access. Handlers take the Drizzle handle
 * as a parameter; tests supply their own real database.
 *
 * INVARIANT — key material: the plaintext key and signing secret
 * appear exactly once, in `generateApiKey`'s return value. Neither is
 * placed in an event payload or echoed in an error message; the key
 * is never persisted, the signing secret only sealed.
 */
import { createHash, randomBytes } from "node:crypto";
import { and, desc, eq, isNull } from "drizzle-orm";
import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import { apiKeys, users, type ApiKeyRow, type UserRow } from "~/db/schema/identity";
import { type CommandResult, reject } from "~/domain/command.server";
import { emitEvent } from "~/domain/events.server";
import { SIGNATURE_WINDOW_MS, signCanonical, signaturesMatch } from "~/domain/identity/api-signing.server";
import type { Sealer } from "~/domain/identity/sealer.server";

/** Every key starts with this, so a leaked key is recognizable as one. */
export const API_KEY_PREFIX = "mgl_";

/** Characters of the key kept for display (`mgl_` plus eight more). */
const DISPLAY_PREFIX_LENGTH = API_KEY_PREFIX.length + 8;

/** Hex SHA-256 of a plaintext key — the stored, looked-up form. */
function hashKey(plaintext: string): string {
  return createHash("sha256").update(plaintext).digest("hex");
}

/** Site admins may manage anyone's keys; everyone else only their own. */
function authorizeKeyManagement(
  db: BetterSQLite3Database,
  actorUserId: number,
  ownerUserId: number,
): CommandResult<never> | null {
  if (actorUserId === ownerUserId) return null;
  const actor = db.select({ admin: users.admin }).from(users).where(eq(users.id, actorUserId)).get();
  if (actor?.admin) return null;
  return reject("authorization", "requires Mingle administrator access");
}

export interface GenerateApiKeyInput {
  /** The user the key will authenticate as. */
  userId: number;
  /** The user asking — the owner, or a site admin. */
  actorUserId: number;
}

/** What GenerateApiKey hands back — the only place the plaintext exists. */
export interface GeneratedApiKey {
  /** The full bearer key; show it once and discard it. */
  key: string;
  /** The HMAC signing secret paired with the key; show it once and discard it. */
  signingSecret: string;
  row: ApiKeyRow;
}

/**
 * GenerateApiKey — mints a new bearer key and signing secret for a user.
 *
 * DOES: inserts an `api_keys` row holding the SHA-256 hash and display
 * prefix of a freshly generated 256-bit key plus the sealed form of a
 * freshly generated 256-bit signing secret, and appends an
 * ApiKeyGenerated event carrying the prefix (never the key or secret),
 * in one transaction. Existing keys stay valid — a user may hold several.
 * REJECTS: unknown or deactivated user; an actor who is neither the
 * user nor a site admin.
 *
 * @returns the plaintext key, the signing secret, and the row, or field errors
 */
export function generateApiKey(
  db: BetterSQLite3Database,
  sealer: Sealer,
  input: GenerateApiKeyInput,
): CommandResult<GeneratedApiKey> {
  const denied = authorizeKeyManagement(db, input.actorUserId, input.userId);
  if (denied) return denied;
  const owner = db.select().from(users).where(eq(users.id, input.userId)).get();
  if (!owner) return reject("user", "does not exist");
  if (!owner.activated) return reject("user", "is deactivated");

  const key = API_KEY_PREFIX + randomBytes(32).toString("base64url");
  const keyPrefix = key.slice(0, DISPLAY_PREFIX_LENGTH);
  const signingSecret = randomBytes(32).toString("base64url");
  return db.transaction((tx) => {
    const row = tx
      .insert(apiKeys)
      .values({ userId: owner.id, keyHash: hashKey(key), keyPrefix, signingSecretSealed: sealer.seal(signingSecret) })
      .returning()
      .get();
    emitEvent(tx, {
      type: "ApiKeyGenerated",
      aggregateType: "User",
      aggregateId: owner.id,
      payload: { apiKeyId: row.id, keyPrefix },
      actorUserId: input.actorUserId,
    });
    return { ok: true, value: { key, signingSecret, row } } as CommandResult<GeneratedApiKey>;
  });
}

export interface RevokeApiKeyInput {
  apiKeyId: number;
  /** The user asking — the key's owner, or a site admin. */
  actorUserId: number;
}

/**
 * RevokeApiKey — permanently disables a key.
 *
 * DOES: stamps the `api_keys` row's `revoked_at` (the row is kept for
 * attribution) and appends an ApiKeyRevoked event, in one transaction.
 * A revoked key fails `authenticateApiKey` from then on.
 * REJECTS: unknown key; a key already revoked; an actor who is neither
 * the owner nor a site admin.
 *
 * @returns the revoked row, or field errors
 */
export function revokeApiKey(
  db: BetterSQLite3Database,
  input: RevokeApiKeyInput,
): CommandResult<ApiKeyRow> {
  const existing = db.select().from(apiKeys).where(eq(apiKeys.id, input.apiKeyId)).get();
  if (!existing) return reject("apiKey", "does not exist");
  const denied = authorizeKeyManagement(db, input.actorUserId, existing.userId);
  if (denied) return denied;
  if (existing.revokedAt) return reject("apiKey", "has already been revoked");

  return db.transaction((tx) => {
    const row = tx
      .update(apiKeys)
      .set({ revokedAt: new Date() })
      .where(eq(apiKeys.id, existing.id))
      .returning()
      .get();
    emitEvent(tx, {
      type: "ApiKeyRevoked",
      aggregateType: "User",
      aggregateId: existing.userId,
      payload: { apiKeyId: existing.id, keyPrefix: existing.keyPrefix },
      actorUserId: input.actorUserId,
    });
    return { ok: true, value: row } as CommandResult<ApiKeyRow>;
  });
}

/**
 * Resolves a presented bearer key to the user it authenticates.
 *
 * DOES: on success, stamps the key's `last_used_at` (the profile page
 * shows it, so a forgotten key can be spotted). A query with a
 * bookkeeping side effect, not a command — no event is recorded, since
 * one row per API request would drown the event log.
 *
 * @param db - the Drizzle handle
 * @param presented - the raw key from the request
 * @returns the authenticated user, or null when the key is malformed,
 *   unknown, revoked, or belongs to a deactivated user
 */
export function authenticateApiKey(
  db: BetterSQLite3Database,
  presented: string,
): UserRow | null {
  if (!presented.startsWith(API_KEY_PREFIX)) return null;
  const match = db
    .select({ key: apiKeys, user: users })
    .from(apiKeys)
    .innerJoin(users, eq(users.id, apiKeys.userId))
    .where(and(eq(apiKeys.keyHash, hashKey(presented)), isNull(apiKeys.revokedAt)))
    .get();
  if (!match || !match.user.activated) return null;
  db.update(apiKeys).set({ lastUsedAt: new Date() }).where(eq(apiKeys.id, match.key.id)).run();
  return match.user;
}

export interface VerifySignedRequestInput {
  /** The access id from the Authorization header — the user's login. */
  login: string;
  /** The canonical request string the server rebuilt from the request. */
  canonical: string;
  /** The base64 signature presented. */
  signature: string;
  /** The X-Mingle-Date value presented, verbatim. */
  date: string;
  /** The server's clock; defaults to now. */
  now?: Date;
}

/**
 * Resolves an HMAC-signed request to the user whose signing secret
 * produced it (legacy `hmac_auth` parity: the access id is the login).
 *
 * DOES: on success, stamps the matching key's `last_used_at`. A query
 * with a bookkeeping side effect, like `authenticateApiKey`.
 *
 * @returns the user, or null when the date is unparseable or outside
 *   ±15 minutes of `now`, the login is unknown or deactivated, or no
 *   live key of that user signs the canonical string to the presented
 *   signature. Every live key with a signing secret is tried, in
 *   timing-safe comparisons.
 */
export function verifySignedRequest(
  db: BetterSQLite3Database,
  sealer: Sealer,
  input: VerifySignedRequestInput,
): UserRow | null {
  const sent = Date.parse(input.date);
  if (Number.isNaN(sent)) return null;
  if (Math.abs((input.now ?? new Date()).getTime() - sent) > SIGNATURE_WINDOW_MS) return null;
  const user = db.select().from(users).where(eq(users.login, input.login.trim().toLowerCase())).get();
  if (!user || !user.activated) return null;
  const keys = db
    .select()
    .from(apiKeys)
    .where(and(eq(apiKeys.userId, user.id), isNull(apiKeys.revokedAt)))
    .all();
  for (const key of keys) {
    if (!key.signingSecretSealed) continue;
    let secret: string;
    try {
      secret = sealer.open(key.signingSecretSealed);
    } catch {
      continue;
    }
    if (signaturesMatch(signCanonical(secret, input.canonical), input.signature)) {
      db.update(apiKeys).set({ lastUsedAt: new Date() }).where(eq(apiKeys.id, key.id)).run();
      return user;
    }
  }
  return null;
}

/** A key as the profile page lists it — never the hash. */
export interface ApiKeySummary {
  id: number;
  keyPrefix: string;
  createdAt: Date;
  lastUsedAt: Date | null;
}

/**
 * The live (unrevoked) keys of a user, newest first, for the profile page.
 *
 * @param db - the Drizzle handle
 * @param userId - the owner
 */
export function listApiKeys(db: BetterSQLite3Database, userId: number): ApiKeySummary[] {
  return db
    .select({
      id: apiKeys.id,
      keyPrefix: apiKeys.keyPrefix,
      createdAt: apiKeys.createdAt,
      lastUsedAt: apiKeys.lastUsedAt,
    })
    .from(apiKeys)
    .where(and(eq(apiKeys.userId, userId), isNull(apiKeys.revokedAt)))
    .orderBy(desc(apiKeys.createdAt), desc(apiKeys.id))
    .all();
}
